version: "3"

services:
  web:
    container_name: plateasapp
    restart: always
    build: .
    ports:
      - "3300:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: plateasdb
    image: mongo
    ports:
      - "27018:27017"
    logging:
      driver: none
